set -g mouse on
set -s set-clipboard on
set -g allow-passthrough on
setw -g mode-keys vi

# Better Copy Mode bindings
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Mouse selection sends to system clipboard via the Ms sequence
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Window and pane management
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r o select-pane -t :.+
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r J swap-pane -D
bind -r K swap-pane -U

bind '"' split-window -v -c "#{pane_current_path}" -l 30%
bind '%' split-window -h -c "#{pane_current_path}" -l 30%
# bind x command-prompt -p "join pane from:"  "join-pane  -l 30% -s '%%'"
# bind b command-prompt -p "break pane to window:"  "break-pane -d -t '%%'"
bind t command-prompt -p "New Pane Title:" "select-pane -T '%%'; set-option -w automatic-rename off; set-option -w automatic-rename on"
# set -g renumber-windows on
set -g automatic-rename on
set -g automatic-rename-format "#{pane_title}"
set -g allow-rename off
# Start with pane borders turned off
set -g pane-border-status off
set -g pane-border-format "#{pane_index} #{pane_title}"

set -g default-terminal "tmux-256color"
# Create a hook that runs whenever the window layout changes
# Logic: If panes > 1, show borders. If panes == 1, hide borders.
set-hook -g window-layout-changed 'if-shell -F "#{>:#{window_panes},1}" "set-option -w pane-border-status top" "set-option -w pane-border-status off"'


# Optimized Overrides: Standardizes TrueColor and Clipboard across xterm/ghostty
set -as terminal-overrides ',xterm*:Ms=\E]52;c;%p2%s\a'
set -as terminal-overrides ',xterm*:RGB'
set -as terminal-overrides ',xterm*:Tc'

# Styled Underscores for Neovim (Smulx = curly, Setulc = colored)
set -as terminal-overrides ',xterm*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',xterm*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] %c '
set-option -g status-right-length 100
# Set TPM plugin path
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"
####
# Plugins
####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

