set -as terminal-overrides ',xterm*:Ms=\E]52;%p1%s;%p2%s\7'
set -as terminal-overrides ',ghostty*:Ms=\E]52;%p1%s;%p2%s\7'
set -g mouse off
setw -g mode-keys vi

# bind -T copy-mode-vi y send-keys -X copy-selection
# bind -T copy-mode-vi y send -X copy-selection-and-cancel
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Window and pane management
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r o select-pane -t :.+
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r J swap-pane -D
bind -r K swap-pane -U

bind '"' split-window -v -c "#{pane_current_path}" -l 30%
bind '%' split-window -h -c "#{pane_current_path}" -l 30%
# bind x command-prompt -p "join pane from:"  "join-pane  -l 30% -s '%%'"
# bind b command-prompt -p "break pane to window:"  "break-pane -d -t '%%'"
bind t command-prompt -p "New Pane Title:" "select-pane -T '%%'; set-option -w automatic-rename off; set-option -w automatic-rename on"
# set -g renumber-windows on
set -g automatic-rename on
set -g automatic-rename-format "#{pane_title}"
set -g allow-rename off
# Start with pane borders turned off
set -g pane-border-status off
set -g pane-border-format "#{pane_index} #{pane_title}"

# Create a hook that runs whenever the window layout changes
# Logic: If panes > 1, show borders. If panes == 1, hide borders.
set-hook -g window-layout-changed 'if-shell -F "#{>:#{window_panes},1}" "set-option -w pane-border-status top" "set-option -w pane-border-status off"'


##
# Styling
##
# Standardize the internal terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',xterm-256color:Ms=\E]52;c;%p2%s\7'

# Force TrueColor (RGB) for Ghostty
# The first part is the value of $TERM outside tmux
set-option -sa terminal-overrides ",xterm-ghostty:Tc"

# Add support for styled underscores 
set -as terminal-overrides ',xterm-ghostty:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',xterm-ghostty:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] %c '
set-option -g status-right-length 100
# Set TPM plugin path
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"
####
# Plugins
####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
